name: default
kind: pipeline
type: docker

steps:
  - name: fetch tags
    image: alpine/git
    commands:
      - git fetch --tags
    when:
      event:
        - tag

  - name: build
    image: golang:1.17-alpine
    commands:
      - go build -v ./...

  - name: release
    image: goreleaser/goreleaser
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
    commands:
      - go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - goreleaser release --clean --release-notes <(git-chglog -t .chglog/RELEASE_CHANGELOG.tpl.md)
    when:
      event:
        - tag