before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - .config-mapper.yml.template
      - CHANGELOG.md
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

gitea_urls:
  api: https://gitea.antoine-langlois.net/api/v1
  download: https://gitea.antoine-langlois.net
release:
  gitea:
    owner: DataHearth
    name: config-mapper
  mode: append
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
