before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
gitea_urls:
  api: https://gitea.antoine-langlois.net/api/v1
  download: https://gitea.antoine-langlois.net
release:
  gitea:
    owner: DataHearth
    name: config-mapper
  mode: append
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
