name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and test

    runs-on: debian-go

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

  release:
    name: Release

    needs: build
    runs-on: debian-go

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Build
        run: go build -v ./...

      - name: Release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          go install github.com/goreleaser/goreleaser@latest
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          goreleaser release --clean --release-notes <(git-chglog -t .chglog/RELEASE_CHANGELOG.tpl.md)
